version: 0.2

phases:
  install:
    commands:
      - echo "Instalando Node.js 24.x e npm..."
      - curl -fsSL https://rpm.nodesource.com/setup_24.x | sudo bash -
      - sudo yum install -y nodejs
      - node -v
      - npm -v

  build:
    commands:
      - echo "Entrando na pasta client..."
      - cd client

      - echo "Instalando dependências..."
      - npm install --legacy-peer-deps --loglevel=error

      - echo "Gerando build..."
      - VITE_API_URL=http://localhost:3001 npm run build